tasks:
  # Hasura Engine
  # ======================
  - name: Hasura Engine
    before: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
    command: make start-be
    openIn: right

  # Hasura Events
  # ======================
  - name: Hasura Events
    command:
      bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4010/healthz)" != "200" ]]; do sleep 5; done'
      && docker-compose up hasura-events-test
      && docker-compose logs -f hasura-events
    openIn: right

  # Hasura Actions
  # ======================
  - name: Hasura Actions
    command:
      bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4020/healthz)" != "200" ]]; do sleep 5; done'
      && docker-compose up hasura-actions-test
      && docker-compose logs -f hasura-actions
    openIn: right

  # GraphQL API
  # ======================
  - name: GraphQL API
    command:
      bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4030/healthz)" != "200" ]]; do sleep 5; done'
      && docker-compose up graphql-api-test
      && docker-compose logs -f graphql-api
    openIn: right

  # SQL Unit Tests
  # ======================
  - name: SQL Unit Tests
    before: make test-sql-start && sleep 20
    command: make test-sql
    openIn: right

  # App Backoffice
  # ======================
  - name: App Backoffice
    before: cd app-backoffice && rm -rf ./.gitpod.lock && npm install && touch ./.gitpod.lock
    command: HELLO=world
      REACT_APP_HASURA_GRAPHQL_ENDPOINT=$(gp url 8080)/v1/graphql
      DANGEROUSLY_DISABLE_HOST_CHECK=true
      CHOKIDAR_USEPOLLING=true
      WDS_SOCKET_PORT=0
      npm start
    openIn: right

  # Unit Tests Backoffice
  # ======================
  - name: Unit Tests Backoffice
    before: cd app-backoffice && echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 1; done
    command: npm test
    openIn: right

  # App Survey
  # ======================
  - name: App Survey
    before: cd app-survey && rm -rf ./.gitpod.lock && npm install && touch ./.gitpod.lock
    command: HELLO=world
      REACT_APP_HASURA_GRAPHQL_ENDPOINT=$(gp url 8080)/v1/graphql
      DANGEROUSLY_DISABLE_HOST_CHECK=true
      CHOKIDAR_USEPOLLING=true
      WDS_SOCKET_PORT=0
      npm start
    openIn: right

  # Unit Tests Survey
  # ======================
  - name: Unit Tests Form
    before: cd app-survey && echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 1; done
    command: npm test
    openIn: right

ports:
  - description: Hasura CLI
    port: 8080
    onOpen: ignore
    visibility: public
  - description: Form App
    port: 3000
    onOpen: open-preview
    visibility: public
  - description: Backoffice App
    port: 3010
    onOpen: ignore
    visibility: public
  - port: 4010
    onOpen: ignore
  - port: 4020
    onOpen: ignore
  - port: 4030
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 8008
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - mikestead.dotenv
    - wayou.vscode-todo-highlight
    - EditorConfig.EditorConfig
    - ms-azuretools.vscode-docker
    - spmeesseman.vscode-taskexplorer
